common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views as p_views
from shopping import views as s_views
from searchkeyword import views as sk_views


urlpatterns = [
    path('common/', include('common.urls')),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('', sk_views.index, name='style'),  # '/' 에 해당되는 path
    path('main/', s_views.main,),
    path('main/', include('shopping.urls')),
    path('searchkeyword/', include('searchkeyword.urls')),
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.style, name='style'),
    path('index', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

searchkeyword/urls.py
from django.urls import path
from . import views, practice


app_name = 'searchkeyword'

urlpatterns = [
    path('', views.index, name='style'),
    path('searchkeyword/result/', practice.complete, name='complete'),


    

]

shopping/urls.py
from django.urls import path
from . import views, main

app_name = 'shopping'

urlpatterns = [
    path('', views.main , name='main'),
    path('main/', main.shopping_cate , name='main_cete'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

        <!-- pybo CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

        <link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/static.datalab/202104010127/css/datalab.css">
        <link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/static.datalab/202104010127/css/graph.css">
        <title></title>
        <script language="javascript">
            //상위 셀렉트로 하위 셀렉트 제어하기
            function showSub(obj) {
        
                f = document.forms.ymd;
        
                if (obj == 1) {
        
                    f.SUB1.style.display = "";
                    f.SUB2.style.display = "none";
                    f.SUB3.style.display = "none";
                    f.SUB4.style.display = "none";
        
                } else if (obj == 2) {
        
                    f.SUB1.style.display = "none";
                    f.SUB2.style.display = "";
                    f.SUB3.style.display = "none";
                    f.SUB4.style.display = "none";
        
                } else if (obj == 3) {
        
                    f.SUB1.style.display = "none";
                    f.SUB2.style.display = "none";
                    f.SUB3.style.display = "";
                    f.SUB4.style.display = "none";
        
                } else {
        
                    f.SUB1.style.display = "none";
                    f.SUB2.style.display = "none";
                    f.SUB3.style.display = "none";
                    f.SUB4.style.display = "";
        
                }
        
            }
        </script>
    </head>
    <body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    <!-- jQuery JS -->

    {% block script %}
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <!-- 자바스크립트 Start -->

    {% endblock %}
    <!-- 자바스크립트 End -->
    </body>

</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'searchkeyword:style' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'pybo:index' %}">게시판</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'shopping:main' %}">쇼핑 차트</a>
            </li>
        </ul>
    </div>
</nav>